name: to_do_list
description: "A To Do List built in Flutter"

publish_to: 'none'

version: 0.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:

  uses-material-design: true

